### ISSUE TITLE
Issue after the "ng serve"

### ISSUE THREAD

**Issue by malqerm** [timofeji/ng2-image-cropper#2]
ERROR in ./node_modules/ng2-canvas-image-cropper/image-cropper.module.ts
Module build failed: Error: C:\POCs\AttachmentsEditor\node_modules\ng2-canvas-image-cropper\image-cropper.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
at AngularCompilerPlugin.getCompiledFile (C:\POCs\AttachmentsEditor\node_modules@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
at plugin.done.then (C:\POCs\AttachmentsEditor\node_modules@ngtools\webpack\src\loader.js:467:39)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by timofeji** [comment]
I broke the npm packaging by accident... I'll fix it when I get the time, but if you need use the cropper you can get the raw component from the lib folder and use it in your project it just won't be modular.
